package com.lukeplechaty.oat;
import com.lukeplechaty.oat.items.ItemChisel;
import com.lukeplechaty.oat.items.ItemMachete;
import com.lukeplechaty.oat.items.ItemSickle;
import com.lukeplechaty.oat.items.Itemmortarandpestle;
import com.lukeplechaty.oat.items.Itemore;
import com.lukeplechaty.oat.items.Itemwork;
import net.minecraft.client.renderer.block.model.ModelResourceLocation;
import net.minecraft.item.Item;
import net.minecraftforge.client.model.ModelLoader;
import net.minecraftforge.common.config.Configuration;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.registry.GameRegistry;
public class setItems
{
	private static String[] MT=new String[]{"wood","stone","iron","gold","diamond","tin","copper","silver","lead","nickel","platinum","aluminum","mithril"};
	private static int[] DG=new int[MT.length];
	public static boolean genores;
	public static Item seed;
	public static Item sodium;
	public static Item sulfur;
	public static Item handel;
	public static Item rock;
	public static Item gem_certus_quartz;
	public static Item gem_sapphire;
	public static Item gem_ruby;
	public static Item gem_peridot;
	public static Item ingot_tin;
	public static Item ingot_copper;
	public static Item ingot_silver;
	public static Item ingot_lead;
	public static Item ingot_nickel;
	public static Item ingot_platinum;
	public static Item ingot_aluminum;
	public static Item ingot_mithril;
	public static Item ingot_cobalt;
	public static Item ingot_ardite;
	public static Item ingot_yellorium;
	public static Item dust_iron;
	public static Item dust_gold;
	public static Item dust_tin;
	public static Item dust_copper;
	public static Item dust_silver;
	public static Item dust_lead;
	public static Item dust_nickel;
	public static Item dust_platinum;
	public static Item dust_aluminum;
	public static Item dust_mithril;
	public static Item dust_cobalt;
	public static Item dust_ardite;
	public static Item dust_yellorium;
	public static Item dust_flour;
	public static Item dust_sodium;
	public static Item dust_sulfur;
	public static Item dust_charcoal;
	public static Item chunk_iron;
	public static Item chunk_gold;
	public static Item chunk_tin;
	public static Item chunk_copper;
	public static Item chunk_silver;
	public static Item chunk_lead;
	public static Item chunk_nickel;
	public static Item chunk_platinum;
	public static Item chunk_aluminum;
	public static Item chunk_mithril;
	public static Item chunk_cobalt;
	public static Item chunk_ardite;
	public static Item chunk_yellorium;
	public static Item lump_iron;
	public static Item lump_gold;
	public static Item lump_tin;
	public static Item lump_copper;
	public static Item lump_silver;
	public static Item lump_lead;
	public static Item lump_nickel;
	public static Item lump_platinum;
	public static Item lump_aluminum;
	public static Item lump_mithril;
	public static Item lump_cobalt;
	public static Item lump_ardite;
	public static Item lump_yellorium;
	public static Item lump_clean_iron;
	public static Item lump_clean_gold;
	public static Item lump_clean_tin;
	public static Item lump_clean_copper;
	public static Item lump_clean_silver;
	public static Item lump_clean_lead;
	public static Item lump_clean_nickel;
	public static Item lump_clean_platinum;
	public static Item lump_clean_aluminum;
	public static Item lump_clean_mithril;
	public static Item lump_clean_cobalt;
	public static Item lump_clean_ardite;
	public static Item lump_clean_yellorium;
	public static Item chiselwood;
	public static Item chiselstone;
	public static Item chiseliron;
	public static Item chiselgold;
	public static Item chiseldiamond;
	public static Item chiseltin;
	public static Item chiselcopper;
	public static Item chiselsilver;
	public static Item chisellead;
	public static Item chiselnickel;
	public static Item chiselplatinum;
	public static Item chiselaluminum;
	public static Item chiselmithril;
	public static Item sicklewood;
	public static Item sicklestone;
	public static Item sickleiron;
	public static Item sicklegold;
	public static Item sicklediamond;
	public static Item sickletin;
	public static Item sicklecopper;
	public static Item sicklesilver;
	public static Item sicklelead;
	public static Item sicklenickel;
	public static Item sickleplatinum;
	public static Item sicklealuminum;
	public static Item sicklemithril;
	public static Item machetewood;
	public static Item machetestone;
	public static Item macheteiron;
	public static Item machetegold;
	public static Item machetediamond;
	public static Item machetetin;
	public static Item machetecopper;
	public static Item machetesilver;
	public static Item machetelead;
	public static Item machetenickel;
	public static Item macheteplatinum;
	public static Item machetealuminum;
	public static Item machetemithril;
	public static Item mortarandpestle;
	public static void config(FMLPreInitializationEvent event)
	{
		Configuration config=new Configuration(event.getSuggestedConfigurationFile());
		config.load();
		DG[0]=config.get("Tools max Damage",MT[0],60).getInt();
		DG[1]=config.get("Tools max Damage",MT[1],120).getInt();
		DG[2]=config.get("Tools max Damage",MT[2],240).getInt();
		DG[3]=config.get("Tools max Damage",MT[3],30).getInt();
		DG[4]=config.get("Tools max Damage",MT[4],1500).getInt();
		DG[5]=config.get("Tools max Damage",MT[5],30).getInt();
		DG[6]=config.get("Tools max Damage",MT[6],30).getInt();
		DG[7]=config.get("Tools max Damage",MT[7],60).getInt();
		DG[8]=config.get("Tools max Damage",MT[8],30).getInt();
		DG[9]=config.get("Tools max Damage",MT[9],60).getInt();
		DG[10]=config.get("Tools max Damage",MT[10],1000).getInt();
		DG[11]=config.get("Tools max Damage",MT[11],30).getInt();
		DG[12]=config.get("Tools max Damage",MT[12],2000).getInt();
		genores=config.get("Generate Ores","ore_gen",false).getBoolean(false);
		config.save();
	}
	public static void init()
	{
		seed=(new Itemore("item_seed"));
		sodium=(new Itemore("item_sodium"));
		sulfur=(new Itemore("item_sulfur"));
		handel=(new Itemore("item_handel"));
		rock=(new Itemore("item_rock"));
		gem_certus_quartz=(new Itemore("gem_certus_quartz"));
		gem_sapphire=(new Itemore("gem_sapphire"));
		gem_ruby=(new Itemore("gem_ruby"));
		gem_peridot=(new Itemore("gem_peridot"));
		ingot_tin=(new Itemore("ingot_tin"));
		ingot_copper=(new Itemore("ingot_copper"));
		ingot_silver=(new Itemore("ingot_silver"));
		ingot_lead=(new Itemore("ingot_lead"));
		ingot_nickel=(new Itemore("ingot_nickel"));
		ingot_platinum=(new Itemore("ingot_platinum"));
		ingot_aluminum=(new Itemore("ingot_aluminum"));
		ingot_mithril=(new Itemore("ingot_mithril"));
		ingot_cobalt=(new Itemore("ingot_cobalt"));
		ingot_ardite=(new Itemore("ingot_ardite"));
		ingot_yellorium=(new Itemore("ingot_yellorium"));
		dust_iron=(new Itemore("dust_iron"));
		dust_gold=(new Itemore("dust_gold"));
		dust_tin=(new Itemore("dust_tin"));
		dust_copper=(new Itemore("dust_copper"));
		dust_silver=(new Itemore("dust_silver"));
		dust_lead=(new Itemore("dust_lead"));
		dust_nickel=(new Itemore("dust_nickel"));
		dust_platinum=(new Itemore("dust_platinum"));
		dust_aluminum=(new Itemore("dust_aluminum"));
		dust_mithril=(new Itemore("dust_mithril"));
		dust_cobalt=(new Itemore("dust_cobalt"));
		dust_ardite=(new Itemore("dust_ardite"));
		dust_yellorium=(new Itemore("dust_yellorium"));
		dust_flour=(new Itemore("dust_flour"));
		dust_sodium=(new Itemore("dust_sodium"));
		dust_sulfur=(new Itemore("dust_sulfur"));
		dust_charcoal=(new Itemore("dust_charcoal"));
		lump_clean_iron=(new Itemwork("lump_clean_iron",2,dust_iron));
		lump_clean_gold=(new Itemwork("lump_clean_gold",2,dust_gold));
		lump_clean_tin=(new Itemwork("lump_clean_tin",2,dust_tin));
		lump_clean_copper=(new Itemwork("lump_clean_copper",2,dust_copper));
		lump_clean_silver=(new Itemwork("lump_clean_silver",2,dust_silver));
		lump_clean_lead=(new Itemwork("lump_clean_lead",2,dust_lead));
		lump_clean_nickel=(new Itemwork("lump_clean_nickel",2,dust_nickel));
		lump_clean_platinum=(new Itemwork("lump_clean_platinum",2,dust_platinum));
		lump_clean_aluminum=(new Itemwork("lump_clean_aluminum",2,dust_aluminum));
		lump_clean_mithril=(new Itemwork("lump_clean_mithril",2,dust_mithril));
		lump_clean_cobalt=(new Itemwork("lump_clean_cobalt",2,dust_cobalt));
		lump_clean_ardite=(new Itemwork("lump_clean_ardite",2,dust_ardite));
		lump_clean_yellorium=(new Itemwork("lump_clean_yellorium",2,dust_yellorium));
		lump_iron=(new Itemwork("lump_iron",1,lump_clean_iron));
		lump_gold=(new Itemwork("lump_gold",1,lump_clean_gold));
		lump_tin=(new Itemwork("lump_tin",1,lump_clean_tin));
		lump_copper=(new Itemwork("lump_copper",1,lump_clean_copper));
		lump_silver=(new Itemwork("lump_silver",1,lump_clean_silver));
		lump_lead=(new Itemwork("lump_lead",1,lump_clean_lead));
		lump_nickel=(new Itemwork("lump_nickel",1,lump_clean_nickel));
		lump_platinum=(new Itemwork("lump_platinum",1,lump_clean_platinum));
		lump_aluminum=(new Itemwork("lump_aluminum",1,lump_clean_aluminum));
		lump_mithril=(new Itemwork("lump_mithril",1,lump_clean_mithril));
		lump_cobalt=(new Itemwork("lump_cobalt",1,lump_clean_cobalt));
		lump_ardite=(new Itemwork("lump_ardite",1,lump_clean_ardite));
		lump_yellorium=(new Itemwork("lump_yellorium",1,lump_clean_yellorium));
		chunk_iron=(new Itemwork("chunk_iron",0,lump_iron));
		chunk_gold=(new Itemwork("chunk_gold",0,lump_gold));
		chunk_tin=(new Itemwork("chunk_tin",0,lump_tin));
		chunk_copper=(new Itemwork("chunk_copper",0,lump_copper));
		chunk_silver=(new Itemwork("chunk_silver",0,lump_silver));
		chunk_lead=(new Itemwork("chunk_lead",0,lump_lead));
		chunk_nickel=(new Itemwork("chunk_nickel",0,lump_nickel));
		chunk_platinum=(new Itemwork("chunk_platinum",0,lump_platinum));
		chunk_aluminum=(new Itemwork("chunk_aluminum",0,lump_aluminum));
		chunk_mithril=(new Itemwork("chunk_mithril",0,lump_mithril));
		chunk_cobalt=(new Itemwork("chunk_cobalt",0,lump_cobalt));
		chunk_ardite=(new Itemwork("chunk_ardite",0,lump_ardite));
		chunk_yellorium=(new Itemwork("chunk_yellorium",0,lump_yellorium));
		chiselwood=(new ItemChisel(MT[0],DG[0],1));
		chiselstone=(new ItemChisel(MT[1],DG[1],2));
		chiseliron=(new ItemChisel(MT[2],DG[2],3));
		chiselgold=(new ItemChisel(MT[3],DG[3],1));
		chiseldiamond=(new ItemChisel(MT[4],DG[4],4));
		chiseltin=(new ItemChisel(MT[5],DG[5],1));
		chiselcopper=(new ItemChisel(MT[6],DG[6],1));
		chiselsilver=(new ItemChisel(MT[7],DG[7],2));
		chisellead=(new ItemChisel(MT[8],DG[8],1));
		chiselnickel=(new ItemChisel(MT[9],DG[9],2));
		chiselplatinum=(new ItemChisel(MT[10],DG[10],4));
		chiselaluminum=(new ItemChisel(MT[11],DG[11],1));
		chiselmithril=(new ItemChisel(MT[12],DG[12],5));
		sicklewood=(new ItemSickle(MT[0],DG[0]));
		sicklestone=(new ItemSickle(MT[1],DG[1]));
		sickleiron=(new ItemSickle(MT[2],DG[2]));
		sicklegold=(new ItemSickle(MT[3],DG[3]));
		sicklediamond=(new ItemSickle(MT[4],DG[4]));
		sickletin=(new ItemSickle(MT[5],DG[5]));
		sicklecopper=(new ItemSickle(MT[6],DG[6]));
		sicklesilver=(new ItemSickle(MT[7],DG[7]));
		sicklelead=(new ItemSickle(MT[8],DG[8]));
		sicklenickel=(new ItemSickle(MT[9],DG[9]));
		sickleplatinum=(new ItemSickle(MT[10],DG[10]));
		sicklealuminum=(new ItemSickle(MT[11],DG[11]));
		sicklemithril=(new ItemSickle(MT[12],DG[12]));
		machetewood=(new ItemMachete(MT[0],DG[0],0,2.0F));
		machetestone=(new ItemMachete(MT[1],DG[1],1,4.0F));
		macheteiron=(new ItemMachete(MT[2],DG[2],2,6.0F));
		machetegold=(new ItemMachete(MT[3],DG[3],0,12.0F));
		machetediamond=(new ItemMachete(MT[4],DG[4],3,8.0F));
		machetetin=(new ItemMachete(MT[5],DG[5],0,2.0F));
		machetecopper=(new ItemMachete(MT[6],DG[6],0,2.0F));
		machetesilver=(new ItemMachete(MT[7],DG[7],1,4.0F));
		machetelead=(new ItemMachete(MT[8],DG[8],0,2.0F));
		machetenickel=(new ItemMachete(MT[9],DG[9],1,4.0F));
		macheteplatinum=(new ItemMachete(MT[10],DG[10],3,8.0F));
		machetealuminum=(new ItemMachete(MT[11],DG[11],0,2.0F));
		machetemithril=(new ItemMachete(MT[12],DG[12],4,12.0F));
		mortarandpestle=(new Itemmortarandpestle("mortar_and_pestle"));
	}
	public static void register()
	{
		GameRegistry.register(seed);
		GameRegistry.register(sodium);
		GameRegistry.register(sulfur);
		GameRegistry.register(handel);
		GameRegistry.register(rock);
		GameRegistry.register(gem_certus_quartz);
		GameRegistry.register(gem_sapphire);
		GameRegistry.register(gem_ruby);
		GameRegistry.register(gem_peridot);
		GameRegistry.register(ingot_tin);
		GameRegistry.register(ingot_copper);
		GameRegistry.register(ingot_silver);
		GameRegistry.register(ingot_lead);
		GameRegistry.register(ingot_nickel);
		GameRegistry.register(ingot_platinum);
		GameRegistry.register(ingot_aluminum);
		GameRegistry.register(ingot_mithril);
		GameRegistry.register(ingot_cobalt);
		GameRegistry.register(ingot_ardite);
		GameRegistry.register(ingot_yellorium);
		GameRegistry.register(dust_iron);
		GameRegistry.register(dust_gold);
		GameRegistry.register(dust_tin);
		GameRegistry.register(dust_copper);
		GameRegistry.register(dust_silver);
		GameRegistry.register(dust_lead);
		GameRegistry.register(dust_nickel);
		GameRegistry.register(dust_platinum);
		GameRegistry.register(dust_aluminum);
		GameRegistry.register(dust_mithril);
		GameRegistry.register(dust_cobalt);
		GameRegistry.register(dust_ardite);
		GameRegistry.register(dust_yellorium);
		GameRegistry.register(dust_flour);
		GameRegistry.register(dust_sodium);
		GameRegistry.register(dust_sulfur);
		GameRegistry.register(dust_charcoal);
		GameRegistry.register(chunk_iron);
		GameRegistry.register(chunk_gold);
		GameRegistry.register(chunk_tin);
		GameRegistry.register(chunk_copper);
		GameRegistry.register(chunk_silver);
		GameRegistry.register(chunk_lead);
		GameRegistry.register(chunk_nickel);
		GameRegistry.register(chunk_platinum);
		GameRegistry.register(chunk_aluminum);
		GameRegistry.register(chunk_mithril);
		GameRegistry.register(chunk_cobalt);
		GameRegistry.register(chunk_ardite);
		GameRegistry.register(chunk_yellorium);
		GameRegistry.register(lump_iron);
		GameRegistry.register(lump_gold);
		GameRegistry.register(lump_tin);
		GameRegistry.register(lump_copper);
		GameRegistry.register(lump_silver);
		GameRegistry.register(lump_lead);
		GameRegistry.register(lump_nickel);
		GameRegistry.register(lump_platinum);
		GameRegistry.register(lump_aluminum);
		GameRegistry.register(lump_mithril);
		GameRegistry.register(lump_cobalt);
		GameRegistry.register(lump_ardite);
		GameRegistry.register(lump_yellorium);
		GameRegistry.register(lump_clean_iron);
		GameRegistry.register(lump_clean_gold);
		GameRegistry.register(lump_clean_tin);
		GameRegistry.register(lump_clean_copper);
		GameRegistry.register(lump_clean_silver);
		GameRegistry.register(lump_clean_lead);
		GameRegistry.register(lump_clean_nickel);
		GameRegistry.register(lump_clean_platinum);
		GameRegistry.register(lump_clean_aluminum);
		GameRegistry.register(lump_clean_mithril);
		GameRegistry.register(lump_clean_cobalt);
		GameRegistry.register(lump_clean_ardite);
		GameRegistry.register(lump_clean_yellorium);
		GameRegistry.register(chiselwood);
		GameRegistry.register(chiselstone);
		GameRegistry.register(chiseliron);
		GameRegistry.register(chiselgold);
		GameRegistry.register(chiseldiamond);
		GameRegistry.register(chiseltin);
		GameRegistry.register(chiselcopper);
		GameRegistry.register(chiselsilver);
		GameRegistry.register(chisellead);
		GameRegistry.register(chiselnickel);
		GameRegistry.register(chiselplatinum);
		GameRegistry.register(chiselaluminum);
		GameRegistry.register(chiselmithril);
		GameRegistry.register(sicklewood);
		GameRegistry.register(sicklestone);
		GameRegistry.register(sickleiron);
		GameRegistry.register(sicklegold);
		GameRegistry.register(sicklediamond);
		GameRegistry.register(sickletin);
		GameRegistry.register(sicklecopper);
		GameRegistry.register(sicklesilver);
		GameRegistry.register(sicklelead);
		GameRegistry.register(sicklenickel);
		GameRegistry.register(sickleplatinum);
		GameRegistry.register(sicklealuminum);
		GameRegistry.register(sicklemithril);
		GameRegistry.register(machetewood);
		GameRegistry.register(machetestone);
		GameRegistry.register(macheteiron);
		GameRegistry.register(machetegold);
		GameRegistry.register(machetediamond);
		GameRegistry.register(machetetin);
		GameRegistry.register(machetecopper);
		GameRegistry.register(machetesilver);
		GameRegistry.register(machetelead);
		GameRegistry.register(machetenickel);
		GameRegistry.register(macheteplatinum);
		GameRegistry.register(machetealuminum);
		GameRegistry.register(machetemithril);
		GameRegistry.register(mortarandpestle);
	}
	public static void registerRenders()
	{
		registerRenders(seed);
		registerRenders(sodium);
	}
	private static void registerRenders(Item item)
	{
		ModelLoader.setCustomModelResourceLocation(item,0,new ModelResourceLocation("oat:"+item.getUnlocalizedName(),"inventory"));
	}
}